/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	cirqlSidebar: [{ type: 'autogenerated', dirName: 'cirql' }],
	transagoSidebar: [{ type: 'autogenerated', dirName: 'transago' }]
};

module.exports = sidebars;
