/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	cirqlSidebar: [{ type: 'autogenerated', dirName: 'cirql' }],
	transactionSidebar: [{ type: 'autogenerated', dirName: 'transaction-tracker' }]
};

module.exports = sidebars;
