name: Publish Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: write-all

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Frontend dependencies
        run: |
          npm i -g pnpm
          pnpm install --no-frozen-lockfile

      - name: Build application
        run: pnpm build

      - name: Upload web app
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
  release:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - package
    steps:
      - name: Publish web app
        uses: actions/deploy-pages@v4
